accounts/urls.py
from django.urls import path

from accounts.views import MyLoginView, MySignupView, MyLogoutView


app_name = 'accounts'

urlpatterns = [
    path('signup/', MySignupView.as_view(), name='signup'),
    path('login/', MyLoginView.as_view(), name='login'),
    path('logout/', MyLogoutView.as_view(), name='logout'),
]

app_poll/urls.py
from django.urls import path
from app_poll.views import IndexView, VoteView, QuestionView, VariantView, TextAnswerView, record_to_model_one_answer, \
    SomeVariantView, record_to_model_some_answers, OutcomeView, QuestionByTypeView, DeleteAnswerView


app_name = 'poll'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('votes/', VoteView.as_view(), name='vote'),
    path('votes/<int:pk>/', QuestionView.as_view(), name='question'),
    path('votes/question/<int:pk>/<str:type>/', QuestionByTypeView.as_view(), name='question_by_type'),
    path('votes/one_answer_question/<int:pk>/', VariantView.as_view(), name='variant'),
    path('votes/one_answer_question/result/<int:pk>/', record_to_model_one_answer, name='result_one_variant'),
    path('votes/some_answers_question/<int:pk>/', SomeVariantView.as_view(), name='some_variant'),
    path('votes/some_answers_question/result/<int:pk>/', record_to_model_some_answers, name='result_some_variant'),
    path('votes/text_one_answer_question/<int:pk>/', TextAnswerView.as_view(), name='text_answer'),
    path('outcome/<int:pk>/', OutcomeView.as_view(), name='outcome'),
    path('delete/<int:pk>/', DeleteAnswerView.as_view(), name='delete'),
]

conf/urls.py
from django.contrib import admin
from django.urls import path, include
from app_poll.views import custom_handler404, custom_handler500

handler404 = custom_handler404
handler500 = custom_handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('app_poll.urls')),
]

app_poll/models.py
from django.db import models
from django.contrib.auth.models import User


class Vote(models.Model):
    title = models.CharField(max_length=50, verbose_name='Опрос')
    published = models.DateTimeField(db_index=True, verbose_name='Открытие опроса')
    published_off = models.DateTimeField(db_index=True, verbose_name='Закрытие опроса')
    content = models.TextField(null=True, blank=True, verbose_name='Описание')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'Опросы'
        verbose_name = 'Опрос'
        ordering = ['-published']


class Question(models.Model):
    vote = models.ForeignKey('Vote', null=True, on_delete=models.CASCADE, verbose_name='Опрос')
    TYPE = (
        ('text', 'Ответ вводом текста'),
        ('one_choice', 'Ответ с выбором одного варианта'),
        ('some_choices', 'Ответ с выбором нескольких вариантов'),
    )
    type_question = models.CharField(max_length=50, choices=TYPE, verbose_name='Тип вопроса')
    text = models.CharField(max_length=100, verbose_name='Вопрос')
    correct_answer = models.CharField(max_length=50, verbose_name='Правильный ответ')

    def __str__(self):
        return self.text

    class Meta:
        verbose_name_plural = 'Вопросы'
        verbose_name = 'Вопрос'
        ordering = ['text']


class Variant(models.Model):
    question = models.ForeignKey('Question', null=True, on_delete=models.PROTECT, verbose_name='Вопрос')
    name_variant = models.CharField(max_length=50, verbose_name='Вариант')

    def __str__(self):
        return self.name_variant

    class Meta:
        verbose_name_plural = 'Варианты'
        verbose_name = 'Вариант'
        ordering = ['name_variant']


class Answer(models.Model):
    answer = models.CharField(max_length=50, verbose_name='Ответ пользователя')
    date_of_answer = models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата и время ответа')
    question = models.ForeignKey('Question', null=True, on_delete=models.PROTECT, verbose_name='Вопрос')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="answer", verbose_name='Пользователь')

    def __str__(self):
        return self.answer

    class Meta:
        verbose_name_plural = 'Ответы'
        verbose_name = 'Ответ'
        ordering = ['answer']

app_poll/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Submit

from app_poll.models import Answer


class AnswerForm(forms.ModelForm):

    class Meta:
        model = Answer

        fields = ('answer',)

    def __init__(self, *args, **kwargs):
        super(AnswerForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_method = 'POST'
        self.helper.layout = Layout(
            Fieldset(
                'answer',
            ),
            ButtonHolder(Submit('submit', 'Перейти к выбору опросов'))
        )

app_poll/views.py
from datetime import datetime
from django.shortcuts import reverse
from django.http import HttpResponseNotFound, HttpResponseServerError, HttpResponseRedirect
from django.views.generic.base import TemplateView
from django.views.generic import DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView
from app_poll.forms import AnswerForm

from app_poll.models import Vote, Question, Variant, Answer


def custom_handler404(request, exception):
    return HttpResponseNotFound('Ресурс не найден!')


def custom_handler500(request):
    return HttpResponseServerError('Ошибка сервера!')


class QuestionByTypeView(LoginRequiredMixin, TemplateView):
    login_url = 'accounts:login'
    template_name = 'app_poll/question_by_type.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['questions'] = Question.objects.filter(type_question=self.kwargs['type'], vote__id=self.kwargs['pk'])
        context['vote'] = Vote.objects.get(id=self.kwargs['pk'])
        context['type'] = Question.objects.filter(type_question=self.kwargs['type']).first()
        return context


class QuestionView(LoginRequiredMixin, TemplateView):
    login_url = 'accounts:login'
    template_name = 'app_poll/questions.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        type_question_set = set()
        for el in Question.objects.filter(vote__id=self.kwargs['pk']):
            type_question_set.add(el.type_question)
        context['types'] = type_question_set
        context['vote'] = Vote.objects.get(id=self.kwargs['pk'])
        return context


class VoteView(LoginRequiredMixin, TemplateView):
    login_url = 'accounts:login'
    template_name = 'app_poll/votes.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        time_now = datetime.now()
        context['votes'] = Vote.objects.filter(published_off__gt=time_now, published__lt=time_now)
        return context


class IndexView(TemplateView):
    template_name = 'app_poll/index.html'


class TextAnswerView(LoginRequiredMixin, CreateView):
    login_url = 'accounts:login'
    template_name = 'app_poll/text.html'
    form_class = AnswerForm
    model = Answer

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['variants'] = Variant.objects.filter(question__id=self.kwargs['pk'])
        context['question'] = Question.objects.get(id=self.kwargs['pk'])
        return context

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.question = Question.objects.get(id=self.kwargs['pk'])
        return super(TextAnswerView, self).form_valid(form)

    def get_success_url(self):
        num = Question.objects.get(id=self.kwargs['pk']).id
        vote_pk = Vote.objects.filter(question__id=num).first().id
        return reverse('poll:question', kwargs={'pk': vote_pk})


class VariantView(LoginRequiredMixin, TemplateView):
    login_url = 'accounts:login'
    template_name = 'app_poll/variants.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['variants'] = Variant.objects.filter(question__id=self.kwargs['pk'])
        context['question'] = Question.objects.get(id=self.kwargs['pk'])
        return context


class SomeVariantView(LoginRequiredMixin, TemplateView):
    login_url = 'accounts:login'
    template_name = 'app_poll/some_variants.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['variants'] = Variant.objects.filter(question__id=self.kwargs['pk'])
        context['question'] = Question.objects.get(id=self.kwargs['pk'])
        return context


def record_to_model_one_answer(request, pk: int):
    answer = Answer()
    num = Vote.objects.filter(question__id=pk).first().id
    variants = Variant.objects.filter(question__id=pk)
    if request.POST:
        for el in variants:
            if el.id == int(request.POST['variant']):
                answer.answer = el.name_variant
                answer.user = request.user
                answer.question = Question.objects.get(id=pk)
                answer.save()
    return HttpResponseRedirect(reverse('poll:question', args=[num]))


def record_to_model_some_answers(request, pk: int):
    answer = Answer()
    num = Vote.objects.filter(question__id=pk).first().id
    variants = Variant.objects.filter(question__id=pk)
    id_list = request.POST.getlist('variantid')
    answer_word = ''
    if request.POST:
        for variant in variants:
            for el in id_list:
                if variant.id == int(el):
                    answer_word += str(variant.name_variant) + ' '
        answer.answer = answer_word
        answer.user = request.user
        answer.question = Question.objects.get(id=pk)
        answer.save()
    return HttpResponseRedirect(reverse('poll:question', args=[num]))


class OutcomeView(LoginRequiredMixin, TemplateView):
    login_url = 'accounts:login'
    template_name = 'app_poll/outcome.html'

    def get(self, request, *args, **kwargs):
        answers_user = Answer.objects.filter(user__id=self.kwargs['pk'])
        questions_answers = {}
        count = 0
        for answer in answers_user:
            key = f'{answer.question.text} Дата и время попытки: ' \
                  f'{str(answer.date_of_answer)[:str(answer.date_of_answer).find(".")]}.'
            if answer.question.type_question != 'some_choices':
                if str(answer.question.correct_answer).lower() == str(answer.answer).lower():
                    count += 1
                    questions_answers[key] = f'Правилный ответ: {str(answer.question.correct_answer)}, ' \
                                             f'а ваш ответ: {str(answer.answer)}. ' \
                                             f'Вы ответили правильно и получаете: +1 балл.'
                else:
                    questions_answers[key] = f'Правилный ответ: {str(answer.question.correct_answer)}, ' \
                                             f'а ваш ответ: {str(answer.answer)}. Вы ответили неправильно.'
            else:
                counter = 0
                question_list = list(map(lambda x: x.lower(), str(answer.question.correct_answer).split()))
                answer_list = list(map(lambda x: x.lower(), str(answer.answer).split()))
                for el in answer_list:
                    if el in question_list:
                        counter += 1
                if counter == len(question_list):
                    count += 1
                    questions_answers[key] = f'Правилный ответ: {str(answer.question.correct_answer)}, ' \
                                             f'а ваш ответ: {str(answer.answer)}. ' \
                                             f'Вы ответили правильно и получаете: +1 балл.'
                else:
                    questions_answers[key] = f'Правилный ответ: {str(answer.question.correct_answer)}, ' \
                                             f'а ваш ответ: {str(answer.answer)}. Вы ответили неправильно.'
        return self.render_to_response({'dict': questions_answers, 'count': count, 'count_2': len(answers_user)})


class DeleteAnswerView(LoginRequiredMixin, DeleteView):
    login_url = 'accounts:login'
    template_name = 'app_poll/delete_answer.html'
    model = Answer

    def get_queryset(self):
        owner = self.request.user.pk
        return self.model.objects.filter(user__id=owner)

    def get_object(self, queryset=None):
        return self.get_queryset()

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['answers'] = Answer.objects.filter(user__id=self.kwargs['pk'])
        return context

    def get_success_url(self):
        return reverse('poll:vote')

app_poll/templates/layout/base.html
{% load crispy_forms_tags %}
{% load bootstrap4 %}
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}Опросник{% endblock %}</title>

  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
{% block css %}{% endblock %}
</head>

<header class="container mt-3">
    <nav class="navbar navbar-expand-lg navbar-blue">
      <a class="navbar-brand mr-4 font-weight-bold" href="{% url 'poll:vote' %}">Опросник</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
              aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-between" id="navbarNav">
        <ul class="navbar-nav col-10"></ul>
        <ul class="navbar-nav col-2 justify-content-end">
          <li class="nav-item active">


            {% if user.is_authenticated %}

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true"
                 aria-expanded="false">{{ user.first_name }} {{ user.last_name }}</a>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'poll:vote' %}">Опросы</a>
                <a class="dropdown-item" href="{% url 'poll:outcome' user.pk %}">Результаты</a>
                <a class="dropdown-item" href="{% url 'poll:delete' user.pk %}">Удаление результатов</a>

              <form action="{% url 'accounts:logout' %}?next=/" method="POST">
                {% csrf_token %}
                {{ form.id_vote }}
                <button class="dropdown-item" type="submit">Выйти</button>
              </form>

              </div>
            </li>

            {% else %}
                <a href="{% url 'accounts:login' %}" class="nav-link font-weight-bold">Вход</a>
            {% endif %}
          </li>
        </ul>
      </div>
    </nav>
  </header>

            {% if user.is_authenticated %}

                <form action="{{ request.META.HTTP_REFERER }}" method="get">
                <input type="submit" class="btn btn-info mb-2" value="Назад">
                </form>

            {% endif %}

<body class="container-fluid">
    <header class="mb-4">
        <h1 class="display-1 text-center">Опросник</h1>
    </header>
    <br>
    <br>

  {% block content %}
  {% endblock %}
</body>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
          integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
          crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
          integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
          crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
          integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
          crossorigin="anonymous"></script>
</html>