app_poll/urls.py
from django.urls import path
from app_poll.views import IndexView, VoteView, QuestionView, VariantView, TextAnswerView, record_to_model_one_answer, \
    SomeVariantView, record_to_model_some_answers, OutcomeView, QuestionByTypeView, DeleteAnswerView


app_name = 'poll'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('votes/', VoteView.as_view(), name='vote'),
    path('votes/<int:pk>/', QuestionView.as_view(), name='question'),
    path('votes/question/<int:pk>/<str:type>/', QuestionByTypeView.as_view(), name='question_by_type'),
    path('votes/one_answer_question/<int:pk>/', VariantView.as_view(), name='variant'),
    path('votes/one_answer_question/result/<int:pk>/', record_to_model_one_answer, name='result_one_variant'),
    path('votes/some_answers_question/<int:pk>/', SomeVariantView.as_view(), name='some_variant'),
    path('votes/some_answers_question/result/<int:pk>/', record_to_model_some_answers, name='result_some_variant'),
    path('votes/text_one_answer_question/<int:pk>/', TextAnswerView.as_view(), name='text_answer'),
    path('outcome/<int:pk>/', OutcomeView.as_view(), name='outcome'),
    path('delete/<int:pk>/', DeleteAnswerView.as_view(), name='delete'),
]

conf/urls.py
from django.contrib import admin
from django.urls import path, include
from app_poll.views import custom_handler404, custom_handler500

handler404 = custom_handler404
handler500 = custom_handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('app_poll.urls')),
]

app_poll/models.py
from django.db import models
from django.contrib.auth.models import User


class Vote(models.Model):
    title = models.CharField(max_length=50, verbose_name='Опрос')
    published = models.DateTimeField(db_index=True, verbose_name='Открытие опроса')
    published_off = models.DateTimeField(db_index=True, verbose_name='Закрытие опроса')
    content = models.TextField(null=True, blank=True, verbose_name='Описание')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'Опросы'
        verbose_name = 'Опрос'
        ordering = ['-published']


class Question(models.Model):
    vote = models.ForeignKey('Vote', null=True, on_delete=models.CASCADE, verbose_name='Опрос')
    TYPE = (
        ('text', 'Ответ вводом текста'),
        ('one_choice', 'Ответ с выбором одного варианта'),
        ('some_choices', 'Ответ с выбором нескольких вариантов'),
    )
    type_question = models.CharField(max_length=50, choices=TYPE, verbose_name='Тип вопроса')
    text = models.CharField(max_length=100, verbose_name='Вопрос')
    correct_answer = models.CharField(max_length=50, verbose_name='Правильный ответ')

    def __str__(self):
        return self.text

    class Meta:
        verbose_name_plural = 'Вопросы'
        verbose_name = 'Вопрос'
        ordering = ['text']


class Variant(models.Model):
    question = models.ForeignKey('Question', null=True, on_delete=models.PROTECT, verbose_name='Вопрос')
    name_variant = models.CharField(max_length=50, verbose_name='Вариант')

    def __str__(self):
        return self.name_variant

    class Meta:
        verbose_name_plural = 'Варианты'
        verbose_name = 'Вариант'
        ordering = ['name_variant']


class Answer(models.Model):
    answer = models.CharField(max_length=50, verbose_name='Ответ пользователя')
    date_of_answer = models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата и время ответа')
    question = models.ForeignKey('Question', null=True, on_delete=models.PROTECT, verbose_name='Вопрос')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="answer", verbose_name='Пользователь')

    def __str__(self):
        return self.answer

    class Meta:
        verbose_name_plural = 'Ответы'
        verbose_name = 'Ответ'
        ordering = ['answer']

app_poll/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Submit

from app_poll.models import Answer


class AnswerForm(forms.ModelForm):

    class Meta:
        model = Answer

        fields = ('answer',)

    def __init__(self, *args, **kwargs):
        super(AnswerForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_method = 'POST'
        self.helper.layout = Layout(
            Fieldset(
                'answer',
            ),
            ButtonHolder(Submit('submit', 'Перейти к выбору опросов'))
        )

app_poll/views.py
from datetime import datetime
from django.shortcuts import reverse
from django.http import HttpResponseNotFound, HttpResponseServerError, HttpResponseRedirect
from django.views.generic.base import TemplateView
from django.views.generic import DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView
from app_poll.forms import AnswerForm

from app_poll.models import Vote, Question, Variant, Answer


def custom_handler404(request, exception):
    return HttpResponseNotFound('Ресурс не найден!')


def custom_handler500(request):
    return HttpResponseServerError('Ошибка сервера!')


class QuestionByTypeView(LoginRequiredMixin, TemplateView):
    login_url = 'accounts:login'
    template_name = 'app_poll/question_by_type.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['questions'] = Question.objects.filter(type_question=self.kwargs['type'], vote__id=self.kwargs['pk'])
        context['vote'] = Vote.objects.get(id=self.kwargs['pk'])
        context['type'] = Question.objects.filter(type_question=self.kwargs['type']).first()
        return context


class QuestionView(LoginRequiredMixin, TemplateView):
    login_url = 'accounts:login'
    template_name = 'app_poll/questions.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        type_question_set = set()
        for el in Question.objects.filter(vote__id=self.kwargs['pk']):
            type_question_set.add(el.type_question)
        context['types'] = type_question_set
        context['vote'] = Vote.objects.get(id=self.kwargs['pk'])
        return context


class VoteView(LoginRequiredMixin, TemplateView):
    login_url = 'accounts:login'
    template_name = 'app_poll/votes.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        time_now = datetime.now()
        context['votes'] = Vote.objects.filter(published_off__gt=time_now, published__lt=time_now)
        return context


class IndexView(TemplateView):
    template_name = 'app_poll/index.html'


class TextAnswerView(LoginRequiredMixin, CreateView):
    login_url = 'accounts:login'
    template_name = 'app_poll/text.html'
    form_class = AnswerForm
    model = Answer

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['variants'] = Variant.objects.filter(question__id=self.kwargs['pk'])
        context['question'] = Question.objects.get(id=self.kwargs['pk'])
        return context

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.question = Question.objects.get(id=self.kwargs['pk'])
        return super(TextAnswerView, self).form_valid(form)

    def get_success_url(self):
        num = Question.objects.get(id=self.kwargs['pk']).id
        vote_pk = Vote.objects.filter(question__id=num).first().id
        return reverse('poll:question', kwargs={'pk': vote_pk})


class VariantView(LoginRequiredMixin, TemplateView):
    login_url = 'accounts:login'
    template_name = 'app_poll/variants.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['variants'] = Variant.objects.filter(question__id=self.kwargs['pk'])
        context['question'] = Question.objects.get(id=self.kwargs['pk'])
        return context


class SomeVariantView(LoginRequiredMixin, TemplateView):
    login_url = 'accounts:login'
    template_name = 'app_poll/some_variants.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['variants'] = Variant.objects.filter(question__id=self.kwargs['pk'])
        context['question'] = Question.objects.get(id=self.kwargs['pk'])
        return context


def record_to_model_one_answer(request, pk: int):
    answer = Answer()
    num = Vote.objects.filter(question__id=pk).first().id
    variants = Variant.objects.filter(question__id=pk)
    if request.POST:
        for el in variants:
            if el.id == int(request.POST['variant']):
                answer.answer = el.name_variant
                answer.user = request.user
                answer.question = Question.objects.get(id=pk)
                answer.save()
    return HttpResponseRedirect(reverse('poll:question', args=[num]))


def record_to_model_some_answers(request, pk: int):
    answer = Answer()
    num = Vote.objects.filter(question__id=pk).first().id
    variants = Variant.objects.filter(question__id=pk)
    id_list = request.POST.getlist('variantid')
    answer_word = ''
    if request.POST:
        for variant in variants:
            for el in id_list:
                if variant.id == int(el):
                    answer_word += str(variant.name_variant) + ' '
        answer.answer = answer_word
        answer.user = request.user
        answer.question = Question.objects.get(id=pk)
        answer.save()
    return HttpResponseRedirect(reverse('poll:question', args=[num]))


class OutcomeView(LoginRequiredMixin, TemplateView):
    login_url = 'accounts:login'
    template_name = 'app_poll/outcome.html'

    def get(self, request, *args, **kwargs):
        answers_user = Answer.objects.filter(user__id=self.kwargs['pk'])
        questions_answers = {}
        count = 0
        for answer in answers_user:
            key = f'{answer.question.text} Дата и время попытки: ' \
                  f'{str(answer.date_of_answer)[:str(answer.date_of_answer).find(".")]}.'
            if answer.question.type_question != 'some_choices':
                if str(answer.question.correct_answer).lower() == str(answer.answer).lower():
                    count += 1
                    questions_answers[key] = f'Правилный ответ: {str(answer.question.correct_answer)}, ' \
                                             f'а ваш ответ: {str(answer.answer)}. ' \
                                             f'Вы ответили правильно и получаете: +1 балл.'
                else:
                    questions_answers[key] = f'Правилный ответ: {str(answer.question.correct_answer)}, ' \
                                             f'а ваш ответ: {str(answer.answer)}. Вы ответили неправильно.'
            else:
                counter = 0
                question_list = list(map(lambda x: x.lower(), str(answer.question.correct_answer).split()))
                answer_list = list(map(lambda x: x.lower(), str(answer.answer).split()))
                for el in answer_list:
                    if el in question_list:
                        counter += 1
                if counter == len(question_list):
                    count += 1
                    questions_answers[key] = f'Правилный ответ: {str(answer.question.correct_answer)}, ' \
                                             f'а ваш ответ: {str(answer.answer)}. ' \
                                             f'Вы ответили правильно и получаете: +1 балл.'
                else:
                    questions_answers[key] = f'Правилный ответ: {str(answer.question.correct_answer)}, ' \
                                             f'а ваш ответ: {str(answer.answer)}. Вы ответили неправильно.'
        return self.render_to_response({'dict': questions_answers, 'count': count, 'count_2': len(answers_user)})


class DeleteAnswerView(LoginRequiredMixin, DeleteView):
    login_url = 'accounts:login'
    template_name = 'app_poll/delete_answer.html'
    model = Answer

    def get_queryset(self):
        owner = self.request.user.pk
        return self.model.objects.filter(user__id=owner)

    def get_object(self, queryset=None):
        return self.get_queryset()

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['answers'] = Answer.objects.filter(user__id=self.kwargs['pk'])
        return context

    def get_success_url(self):
        return reverse('poll:vote')

app_poll/templates/app_poll/delete_answer.html
{% extends "layout/base.html" %}
{% load crispy_forms_tags %}
{% block title %}Вопросы по типу{% endblock %}

{% block css %}
<style>
body {
      background-color: #F6F2E6;
    }
</style>
{% endblock %}

{% block content %}
<h1>Вы действительно хотите удалить следующие данные? После удаления вы окажетесь на странице с опросами.</h1>
    <br>
    {% for answer in answers %}
        <h3>Вопрос: {{ answer.question.text }} Ваш ответ: {{ answer.answer }}</h3>
    {% endfor %}
    <form method="post">
    {% csrf_token %}
    {{ form|crispy  }}
    <br>
    <input type="submit" class="btn btn-info mb-2" value="Подтвердить удаление">
    </form>
{% endblock %}

app_poll/templates/app_poll/index.html
{% extends "layout/base.html" %}
{% load crispy_forms_tags %}
{% block title %}Домашняя страница{% endblock %}

{% block css %}
<style>
body {
      background-color: #F6F2E6;
    }
</style>
{% endblock %}

{% block content %}


<div class="card">
<div class="card-body">
<h4 class="card-title">Добрый день! Вы попали на сайт с опросами пользователей. После регистрации вам станут доступны
  для просмотра опросы с вопросами. После прохождения опроса вы можете просмотреть таблицу с результатами.</h4>
</div>
</div>


{% endblock %}

app_poll/templates/app_poll/outcome.html
{% extends "layout/base.html" %}
{% load crispy_forms_tags %}
{% block title %}Результаты{% endblock %}

{% block css %}
<style>
body {
      background-color: #F6F2E6;
    }
</style>
{% endblock %}

{% block content %}
<h1>Итоги прохождения опросов:</h1>

    {% for key, value in dict.items %}
        <h5>Вопрос: {{ key }}</h5>
        <p>{{ value }}</p>
    {% endfor %}
    <h5>Количество правильных ответов: {{ count }} из {{ count_2 }} </h5>

{% endblock %}

app_poll/templates/app_poll/question_by_type.html
{% extends "layout/base.html" %}
{% load crispy_forms_tags %}
{% block title %}Вопросы{% endblock %}

{% block css %}
<style>
body {
      background-color: #F6F2E6;
    }
</style>
{% endblock %}

{% block content %}
<h1>Опрос - "{{ vote }}". Тип вопроса - {{ type.get_type_question_display }}</h1>
    <br>
    {% for question in questions %}
            {% if question.type_question == 'one_choice' %}
                <h2><a href="{% url 'poll:variant' question.pk %}">{{ question.text }}</a></h2>
            {% elif question.type_question == 'text' %}
                <h2><a href="{% url 'poll:text_answer' question.pk %}">{{ question.text }}</a></h2>
            {% else %}
                <h2><a href="{% url 'poll:some_variant' question.pk %}">{{ question.text }}</a></h2>
            {% endif %}
            <br>
    {% endfor %}
{% endblock %}

app_poll/templates/app_poll/questions.html
{% extends "layout/base.html" %}
{% load crispy_forms_tags %}
{% block title %}Вопросы по типу{% endblock %}

{% block css %}
<style>
body {
      background-color: #F6F2E6;
    }
</style>
{% endblock %}

{% block content %}
<h1>Все вопросы, относящиеся к опросу - "{{ vote }}".</h1>
<h1>Выберите вопросы по типу:</h1>
    <br>
    {% for type in types %}
            {% if type == 'one_choice' %}
                <h2><a href="{% url 'poll:question_by_type' vote.pk type %}">Ответ с выбором одного варианта</a></h2>
            {% elif type == 'text' %}
                <h2><a href="{% url 'poll:question_by_type' vote.pk type %}">Ответ вводом текста</a></h2>
            {% else %}
                <h2><a href="{% url 'poll:question_by_type' vote.pk type %}">Ответ с выбором нескольких вариантов</a></h2>
            {% endif %}
            <br>
    {% endfor %}
{% endblock %}

app_poll/templates/app_poll/some_variants.html
{% extends "layout/base.html" %}
{% load crispy_forms_tags %}
{% block title %}Вопрос с одним вариантом ответа{% endblock %}

{% block css %}
<style>
body {
      background-color: #F6F2E6;
    }
</style>
{% endblock %}

{% block content %}
<h1>Варианты ответов к вопросу - "{{ question }}":</h1>
    <br>

        <form method="post" action="{% url 'poll:result_some_variant' question.pk %}">
        {% csrf_token %}

            {% for variant in variants %}

            <input type="checkbox" id="{{ variant.id }}" name="variantid" value="{{ variant.pk }}">
            <label for="{{ variant.id }}"> {{ variant.name_variant }} </label><br>

        <br>
            {% endfor %}
            <input type="submit" class="btn btn-info mb-2" value="Подтвердить ответ">
        </form>


{% endblock %}

app_poll/templates/app_poll/text.html
{% extends "layout/base.html" %}
{% load crispy_forms_tags %}
{% block title %}Вопрос с вводом ответа текстом{% endblock %}

{% block css %}
<style>
body {
      background-color: #F6F2E6;
    }
</style>
{% endblock %}

{% block content %}
<h1>Введите в поле ваш ответ на вопрос - "{{ question }}":</h1>
    <br>
    <form method="post" enctype="multipart/form-data" action="{% url 'poll:text_answer' question.pk %}">
    {% csrf_token %}
    {{ form|crispy  }}
    <br>
    <input type="submit" class="btn btn-info mb-2" value="Подтвердить ответ">
    </form>
{% endblock %}

app_poll/templates/app_poll/variants.html
{% extends "layout/base.html" %}
{% load crispy_forms_tags %}
{% block title %}Вопрос с одним вариантом ответа{% endblock %}

{% block css %}
<style>
body {
      background-color: #F6F2E6;
    }
</style>
{% endblock %}

{% block content %}
<h1>Варианты ответов к вопросу - "{{ question }}":</h1>
    <br>

        <form method="post" action="{% url 'poll:result_one_variant' question.pk %}">
        {% csrf_token %}

            {% for variant in variants %}
            <input type="radio" name="variant{{ forloop.parentloop.counter }}" id="variant{{ forloop.counter }}" value="{{ variant.pk }}" />
            <label for="variant{{ forloop.counter }}">{{ variant.name_variant }}</label><br />

        <br>
            {% endfor %}
            <input type="submit" class="btn btn-info mb-2" value="Подтвердить ответ">
        </form>


{% endblock %}

app_poll/templates/app_poll/votes.html
{% extends "layout/base.html" %}
{% load crispy_forms_tags %}
{% block title %}Опросы{% endblock %}

{% block css %}
<style>
body {
      background-color: #F6F2E6;
    }
</style>
{% endblock %}

{% block content %}
<h1>Все опросы:</h1>
    <br>
    {% for vote in votes %}
        <h2><a href="{% url 'poll:question' vote.pk %}">{{ vote.title }}</a></h2>
        <p>{{ vote.content }}</p>
    {% endfor %}
{% endblock %}